# This is a development only compose file which will have default values to fallback to so that this application can be run on any device regardless if .env is present or not (it won't be present by default if cloning from github).
# If this ever goes to production, further handling will be needed for this compose file due to the default values.
version: "3"

services:

  # API for the artists api container.
  art-gallery-api-artists:
    image: 127.0.0.1:5000/art-gallery-express-app
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - node_modules:/art-gallery-api/node_modules
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-artists-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
    depends_on:
      - art-gallery-database
    command: npm run dev

  # API for the artworks api container.
  art-gallery-api-artworks:
    image: 127.0.0.1:5000/art-gallery-express-app
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - node_modules:/art-gallery-api/node_modules
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-artworks-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
    depends_on:
      - art-gallery-database
    command: npm run dev

  # API for the users api container.
  art-gallery-api-users:
    image: 127.0.0.1:5000/art-gallery-express-app
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - node_modules:/art-gallery-api/node_modules
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-users-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
    depends_on:
      - art-gallery-database
    command: npm run dev

  # Database for the artists.
  art-gallery-artists-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.
  
  # Database for the artists.
  art-gallery-artworks-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27019:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.

  # Database for the users.
  art-gallery-users-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27020:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.

volumes:
  mongo-db:
  node_modules: