# This is a development only compose file which will have default values to fallback to so that this application can be run on any device regardless if .env is present or not (it won't be present by default if cloning from github).
# If this ever goes to production, further handling will be needed for this compose file due to the default values.
version: "3"

services:

  # Nginx
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # API for the artists api container.
  art-gallery-api-artists:
    image: 127.0.0.1:5000/art-gallery-artists-api-service
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - art-gallery-artists-node_modules:/art-gallery-api/node_modules
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME:-art-gallery-artists-api}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-artists-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
      - REDIS_IP=${REDIS_IP:-art-gallery-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - art-gallery-redis
      - art-gallery-artists-database
    command: npm run dev

  # API for the artworks api container.
  art-gallery-api-artworks:
    image: 127.0.0.1:5000/art-gallery-artworks-api-service
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - art-gallery-artworks-node_modules:/art-gallery-api/node_modules
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME:-art-gallery-artworks-api}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-artworks-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
      - REDIS_IP=${REDIS_IP:-art-gallery-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - art-gallery-redis
      - art-gallery-artworks-database
    command: npm run dev

  # API for the users api container.
  art-gallery-api-users:
    image: 127.0.0.1:5000/art-gallery-users-api-service
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - art-gallery-users-node_modules:/art-gallery-api/node_modules
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME:-art-gallery-users-api}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-users-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
      - REDIS_IP=${REDIS_IP:-art-gallery-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - art-gallery-redis
      - art-gallery-users-database
    command: npm run dev

  # API for the authentication api container.
  art-gallery-api-authentication:
    image: 127.0.0.1:5000/art-gallery-authentication-api-service
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - art-gallery-authentication-node_modules:/art-gallery-api/node_modules
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME:-art-gallery-authentication-api}
      - NODE_ENV=${NODE_ENV:-development} 
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
      - REDIS_IP=${REDIS_IP:-art-gallery-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
    depends_on:
      - art-gallery-redis
    command: npm run dev

  # Database for the artists.
  art-gallery-artists-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - art-gallery-artists-mongo-db:/data/db
    ports:
      - "27018:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.
  
  # Database for the artists.
  art-gallery-artworks-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - art-gallery-artworks-mongo-db:/data/db
    ports:
      - "27019:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.

  # Database for the users.
  art-gallery-users-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - art-gallery-users-mongo-db:/data/db
    ports:
      - "27020:27017" # Remove port binding once we know this is working - Using this with mongo DB Compass to check data.

  # Redis for managing express sessions.
  art-gallery-redis:
    image: redis:latest

volumes:
  art-gallery-artists-mongo-db:
  art-gallery-artworks-mongo-db:
  art-gallery-users-mongo-db:
  art-gallery-artists-node_modules:
  art-gallery-artworks-node_modules:
  art-gallery-users-node_modules:
  art-gallery-authentication-node_modules: