# This is a development only compose file which will have default values to fallback to so that this application can be run on any device regardless if .env is present or not (it won't be present by default if cloning from github).
# If this ever goes to production, further handling will be needed for this compose file due to the default values.
version: "3"

services:

  art-gallery-api:
    image: 127.0.0.1:5000/art-gallery-express-app
    build:
      context: ./art-gallery-api
    volumes:
      - ./art-gallery-api:/art-gallery-api
      - node_modules:/art-gallery-api/node_modules
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=${APP_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development} 
      - MONGO_IP=${MONGO_IP:-art-gallery-database}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - MONGO_USER=${MONGO_USER:-mongouser}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-password}
      - COOKIE_KEY=${COOKIE_KEY:-superawesomecookiekeythatIshouldprobablyhandlebetterwithrandomstringsbutIjustneedsomethingquickfornow}
    depends_on:
      - art-gallery-database
    command: npm run dev

  art-gallery-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      # Small note regarding this, I'm only exposing the port for the database so I can access it via MongoDBCompass so that I can see the entries being added - this should probably be removed in production since there's no need to expose the port since the app and database exist in the same docker network.
      - "27018:27017" 

volumes:
  mongo-db:
  node_modules: